In [2]:
from collections import Counter, deque
import numpy as np

In [14]:
example_input = """
5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
"""

example_2_input = """
11111
19991
19191
19991
11111
"""

puzzle_input = """
4836484555
4663841772
3512484556
1481547572
7741183422
8683222882
4215244233
1544712171
5725855786
1717382281
"""

In [86]:
lines = puzzle_input.split()

adjacent_offsets = [
    (1, 0),
    (1, 1),
    (1, -1),
    (0, 1),
    (0, -1),
    (-1, 0),
    (-1, 1),
    (-1, -1)
]

In [89]:
octos = np.array([list(map(int, list(line))) for line in lines])
rows = octos.shape[0]
cols = octos.shape[1]
flash_count = 0
synch_step = None
print("Starting state")
print(octos)
for step in range(300):
    # print(f"Step {step+1}:")
    # increment energy levels by 1
    octos += 1
    # loop
    # check if any energy level is > 9
    new_flashed = flashed = set(zip(*np.where(octos > 9)))
    # flash energy levels above 9
    while len(new_flashed) > 0:
    # increment adjacent by 1 for each octopus that flashed
        for loc in new_flashed:
            for offset in adjacent_offsets:
                adjacent = tuple(map(lambda i, j: i + j, loc, offset))
                if 0<=adjacent[0]<rows and 0<=adjacent[1]<cols and adjacent not in flashed:
                    octos[adjacent] += 1
        new_flashed = set(zip(*np.where(octos > 9))) - flashed
        flashed = flashed | new_flashed
    # set any flashed to 0
    octos = np.where(octos>9, 0, octos)
    if np.all(octos==0):
        synch_step = step + 1
        print(f"Sync step at {synch_step}")
        print(octos)
    flash_count += len(flashed)
print(octos)
print(f"Flash count: {flash_count}")
print(f"Sync step was {synch_step}")

Starting state
[[4 8 3 6 4 8 4 5 5 5]
 [4 6 6 3 8 4 1 7 7 2]
 [3 5 1 2 4 8 4 5 5 6]
 [1 4 8 1 5 4 7 5 7 2]
 [7 7 4 1 1 8 3 4 2 2]
 [8 6 8 3 2 2 2 8 8 2]
 [4 2 1 5 2 4 4 2 3 3]
 [1 5 4 4 7 1 2 1 7 1]
 [5 7 2 5 8 5 5 7 8 6]
 [1 7 1 7 3 8 2 2 8 1]]
Sync step at 227
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Sync step at 237
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Sync step at 247
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Sync step 

In [79]:
a = np.zeros((10,10), dtype=int)
b = np.ones((10,10), dtype=int)
np.all(a==0)

True